title: 도토리크라프트
baseURL: 'https://dotoricraft.netlify.app'

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true
newContentEditor: code
markup:
  goldmark:
    renderer:
      unsafe: true
