title: 도토리크라프트
description: |
  도토리크라프트는 가죽을 주재료로 지갑이나 소품과 가방을 만들고 있습니다.
  한명의 디자이너가 디자인하고 소재를 골라 직접 제작하는 디자인 핸드메이드 브랜드입니다.
  오래두고 아끼며 사용할 물건을 만들겠다는 생각으로 여러번 고쳐 완성된 디자인에 한땀 한땀 정성들여 바느질하고 꼼꼼하게 마감합니다.
keywords: "가죽공방, 가죽공예, 주문제작, 원데이클래스, 카드지갑"
images:
- /assets/dotoricraft.jpg
- /assets/dotoricraft.png
brand:
  logoType: /assets/47fcef1c71f8d.png
  logoMark: /assets/9d904e09a0704.png
  logoMarkWhite: /assets/23be8bb3feac7.png
  logo: /assets/d05cbd88f6c82.png

store:
  representative: 여연주
  registration: 104-17-05284
  mailOrder:
    number: 2020-서울중구-0058
    url: http://www.ftc.go.kr/bizCommPop.do?wrkr_no=1041705284
  address: 서울 중구 충무로 50-7 (을지로3가) 306호 우) 04549
  location:
    kakao: https://map.kakao.com/?urlX=498515&urlY=1129470&urlLevel=3&itemId=1089815069
    naver: http://naver.me/FdsoNrf3
  phone: 010-8779-0855
  email: dotoricraft@gmail.com
  businessHours: 월~금 11:00-18:30
  termsOfuse: '/terms-of-use'
  privacyPolicy: '/privacy-policy'
  links:
    instagram: https://www.instagram.com/dotori_yeo/
    youtube: https://www.youtube.com/user/zooo0079
    naverShopping: https://shopping.naver.com/living/handmade/stores/100125606
    etsy: https://www.etsy.com/shop/DotoriCraft
  footerLinks:
  - brand: instagram
    url: https://www.instagram.com/dotori_yeo/
  - brand: youtube
    url: https://www.youtube.com/user/zooo0079
  - brand: naver
    url: https://shopping.naver.com/living/handmade/stores/100125606
  - brand: etsy
    url: https://www.etsy.com/shop/DotoriCraft
  share:
  - kakaotalk
  - facebook
  - twitter
  - telegram

product:
  colorScheme:
    베이지: '#eadeb4'
    블랙: '#000000'
    오랜지: '#ff9800'
    레드: '#f44336'
    카라멜: '#c28318'
    올리브: '#747f1a'
    진밤: '#5b3d3d'
    노랑: '#ffd900'
    핑크: '#fea3d7'
    레몬: '#fff5b9'
    스카이: '#9ae0fb'
